import { NextResponse } from 'next/server';
import { requireAuthContext } from '../../../lib/repository/finalizations';
import crypto from 'node:crypto';
import { PROVIDERS } from '../../../lib/integrations/providers';
import { encryptVaultPayload } from '../../../lib/vault';

function clean(v,max=300){return String(v||'').trim().slice(0,max);}
export async function GET(){const ctx=await requireAuthContext();if(ctx.error)return NextResponse.json({error:ctx.error},{status:ctx.status});const {data,error}=await ctx.db.from('integration_connections').select('id,provider,display_name,status,auth_mode,config_json,last_synced_at,last_error,created_at').eq('organization_id',ctx.organization.id).order('created_at',{ascending:true});if(error)return NextResponse.json({error:'integration_load_failed',detail:error.message},{status:500});return NextResponse.json({providers:PROVIDERS,connections:data||[]});}
export async function POST(request){const ctx=await requireAuthContext();if(ctx.error)return NextResponse.json({error:ctx.error},{status:ctx.status});if(!['owner','admin'].includes(ctx.membership.role))return NextResponse.json({error:'admin_required'},{status:403});const body=await request.json();const provider=clean(body.provider,40);if(!PROVIDERS[provider])return NextResponse.json({error:'unsupported_provider'},{status:400});const config=body.config&&typeof body.config==='object'?body.config:{};const safeConfig={};for(const key of ['repository','projectId','teamId','accountId','folderId','mode'])if(config[key]!=null)safeConfig[key]=clean(config[key],300);const {data,error}=await ctx.db.from('integration_connections').insert({organization_id:ctx.organization.id,provider,display_name:clean(body.displayName,120)||PROVIDERS[provider].label,status:'configured',auth_mode:clean(body.authMode,30)||'environment',config_json:safeConfig,created_by:ctx.user.id}).select('id,provider,display_name,status,auth_mode,config_json,last_synced_at,last_error,created_at').single();if(error)return NextResponse.json({error:'integration_create_failed',detail:error.message},{status:500});let webhookSecret=null;const secretToStore=provider==='stripe'?(clean(body.webhookSecret,500)||null):(webhookSecret=crypto.randomBytes(32).toString('base64url'));if(secretToStore){try{const enc=encryptVaultPayload({webhookSecret:secretToStore});const {error:secretError}=await ctx.db.from('integration_secrets').insert({connection_id:data.id,encrypted_payload:enc.ciphertext,payload_iv:enc.iv,payload_tag:enc.tag});if(secretError)throw secretError;}catch(err){await ctx.db.from('integration_connections').delete().eq('id',data.id);return NextResponse.json({error:'integration_secret_setup_failed',detail:err.message},{status:500});}}return NextResponse.json({connection:data,webhookSecret:provider==='stripe'?null:webhookSecret});}
