-- Finalize.page Phase 1C: trusted artifact-processing pipeline
-- Run AFTER phase1-schema.sql and phase1b-migration.sql.

create type public.processing_job_status as enum (
  'QUEUED','RUNNING','WAITING_EXTERNAL','SUCCEEDED','RETRY','DEAD_LETTER','CANCELLED'
);

alter table public.artifacts
  add column if not exists detected_mime_type text,
  add column if not exists signature_status text not null default 'PENDING',
  add column if not exists archive_scan_status text not null default 'NOT_APPLICABLE',
  add column if not exists privacy_scan_status text not null default 'PENDING',
  add column if not exists parser_status text not null default 'PENDING',
  add column if not exists redaction_status text not null default 'PENDING',
  add column if not exists pii_summary jsonb not null default '{}'::jsonb,
  add column if not exists extracted_text_key text,
  add column if not exists derived_prefix text,
  add column if not exists safe_for_ai boolean not null default false,
  add column if not exists retention_delete_after timestamptz,
  add column if not exists security_completed_at timestamptz,
  add column if not exists processing_completed_at timestamptz;

create table if not exists public.processing_jobs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  finalization_id uuid not null references public.finalizations(id) on delete cascade,
  artifact_id uuid not null references public.artifacts(id) on delete cascade,
  job_type text not null,
  status public.processing_job_status not null default 'QUEUED',
  priority integer not null default 100,
  attempts integer not null default 0,
  max_attempts integer not null default 4,
  available_at timestamptz not null default now(),
  lease_until timestamptz,
  worker_id text,
  input jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  last_error text,
  started_at timestamptz,
  completed_at timestamptz,
  dead_lettered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (artifact_id, job_type)
);

create index if not exists processing_jobs_claim_idx
  on public.processing_jobs(status, available_at, priority, created_at)
  where status in ('QUEUED','RETRY');
create index if not exists processing_jobs_artifact_idx on public.processing_jobs(artifact_id, created_at);

create table if not exists public.artifact_privacy_findings (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  finalization_id uuid not null references public.finalizations(id) on delete cascade,
  artifact_id uuid not null references public.artifacts(id) on delete cascade,
  category text not null,
  label text not null,
  count integer not null default 1 check (count > 0),
  sensitivity text not null default 'PERSONAL',
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists artifact_privacy_findings_artifact_idx on public.artifact_privacy_findings(artifact_id);

create table if not exists public.artifact_processing_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  finalization_id uuid not null references public.finalizations(id) on delete cascade,
  artifact_id uuid not null references public.artifacts(id) on delete cascade,
  job_id uuid references public.processing_jobs(id) on delete set null,
  stage text not null,
  state text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists artifact_processing_events_artifact_idx on public.artifact_processing_events(artifact_id, created_at desc);

alter table public.processing_jobs enable row level security;
alter table public.artifact_privacy_findings enable row level security;
alter table public.artifact_processing_events enable row level security;

create policy "members read processing jobs" on public.processing_jobs
  for select using (public.is_org_member(organization_id));
create policy "members read artifact privacy findings" on public.artifact_privacy_findings
  for select using (public.is_org_member(organization_id));
create policy "members read artifact processing events" on public.artifact_processing_events
  for select using (public.is_org_member(organization_id));
-- Writes remain server/service-role only.

-- Atomic job claiming prevents two workers from processing the same job.
create or replace function public.claim_finalize_processing_job(p_worker_id text, p_lease_seconds integer default 120)
returns setof public.processing_jobs
language plpgsql
security definer set search_path = public
as $$
declare
  picked uuid;
begin
  select id into picked
  from public.processing_jobs
  where (
      status in ('QUEUED','RETRY')
      and available_at <= now()
    ) or (
      status = 'RUNNING'
      and lease_until is not null
      and lease_until < now()
    )
  order by priority asc, available_at asc, created_at asc
  for update skip locked
  limit 1;

  if picked is null then
    return;
  end if;

  return query
  update public.processing_jobs
  set status = 'RUNNING',
      attempts = attempts + 1,
      worker_id = p_worker_id,
      lease_until = now() + make_interval(secs => greatest(30, p_lease_seconds)),
      started_at = coalesce(started_at, now()),
      updated_at = now()
  where id = picked
  returning *;
end;
$$;

revoke all on function public.claim_finalize_processing_job(text, integer) from public;
grant execute on function public.claim_finalize_processing_job(text, integer) to service_role;
