-- Finalize.page Phase 3: customer privacy + data-control plane
-- Run AFTER phase2-migration.sql.

create table if not exists public.workspace_privacy_settings (
  organization_id uuid primary key references public.organizations(id) on delete cascade,
  ai_processing_enabled boolean not null default true,
  allow_business_ai boolean not null default true,
  allow_confidential_ai boolean not null default false,
  allow_restricted_ai boolean not null default false,
  require_redaction_for_ai boolean not null default true,
  source_retention_days integer not null default 30 check (source_retention_days between 1 and 3650),
  derived_retention_days integer not null default 30 check (derived_retention_days between 1 and 3650),
  evidence_retention_days integer not null default 365 check (evidence_retention_days between 1 and 3650),
  guest_link_ttl_days integer not null default 7 check (guest_link_ttl_days between 1 and 90),
  auto_revoke_guests_on_finalize boolean not null default true,
  auto_destroy_credentials_on_finalize boolean not null default true,
  data_region text not null default 'north-america' check (data_region in ('north-america','canada','united-states','europe','custom')),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.privacy_disposal_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  finalization_id uuid references public.finalizations(id) on delete cascade,
  artifact_id uuid references public.artifacts(id) on delete cascade,
  request_type text not null check (request_type in ('artifact_delete','finalization_delete','guest_revoke','credential_destroy','account_export','account_delete')),
  status text not null default 'scheduled' check (status in ('scheduled','processing','completed','failed','cancelled')),
  reason text,
  execute_after timestamptz not null default now(),
  requested_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  failure_detail text,
  created_at timestamptz not null default now()
);

create table if not exists public.privacy_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  finalization_id uuid references public.finalizations(id) on delete cascade,
  artifact_id uuid references public.artifacts(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.artifacts
  add column if not exists ai_policy_decision jsonb not null default '{}'::jsonb,
  add column if not exists ai_blocked_reason text,
  add column if not exists privacy_policy_version text not null default 'phase3.v1';

create index if not exists privacy_disposal_due_idx on public.privacy_disposal_requests(status, execute_after) where status='scheduled';
create index if not exists privacy_events_org_idx on public.privacy_events(organization_id, created_at desc);

alter table public.workspace_privacy_settings enable row level security;
alter table public.privacy_disposal_requests enable row level security;
alter table public.privacy_events enable row level security;

create policy "members read privacy settings" on public.workspace_privacy_settings for select using (public.is_org_member(organization_id));
create policy "admins update privacy settings" on public.workspace_privacy_settings for all using (
  exists(select 1 from public.memberships m where m.organization_id=workspace_privacy_settings.organization_id and m.user_id=auth.uid() and m.role in ('owner','admin'))
) with check (
  exists(select 1 from public.memberships m where m.organization_id=workspace_privacy_settings.organization_id and m.user_id=auth.uid() and m.role in ('owner','admin'))
);
create policy "members read disposal requests" on public.privacy_disposal_requests for select using (public.is_org_member(organization_id));
create policy "members read privacy events" on public.privacy_events for select using (public.is_org_member(organization_id));
-- Disposal/privacy event writes remain server/service-role controlled.

insert into public.workspace_privacy_settings (organization_id)
select id from public.organizations
on conflict (organization_id) do nothing;
