'use client';

import { useState } from 'react';
import Link from 'next/link';
import { AppShell } from '../../components/app-shell';
import { Icon } from '../../components/icons';
import { readiness, useFinalizeStore } from '../../lib/finalize-store';

function NewFinalization({onClose,onCreate,templates,defaultTemplate=''}){
  const [title,setTitle]=useState('');const [client,setClient]=useState('');const [templateKey,setTemplateKey]=useState(defaultTemplate);const template=templates.find((t)=>t.key===templateKey);
  async function submit(e){e.preventDefault();if(!title.trim())return;const item=await onCreate({title:title.trim(),client:client.trim()||'New client',type:template?.name||'Custom',templateKey:templateKey||null});window.location.href=`/app/f/${item.id}`;}
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal-card phase2-modal" onMouseDown={(e)=>e.stopPropagation()}><div className="modal-kicker">New finalization</div><h2>What are you finishing?</h2><p>Start from a definition-of-done template, then tailor the gates inside the Room.</p><form onSubmit={submit} className="modal-form"><label>Finalization name<input autoFocus value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Acme website launch"/></label><label>Client / counterpart<input value={client} onChange={(e)=>setClient(e.target.value)} placeholder="Acme & Co."/></label><label>Finalize Spec<select value={templateKey} onChange={(e)=>setTemplateKey(e.target.value)}><option value="">Custom definition of done</option>{templates.map((t)=><option key={t.key} value={t.key}>{t.name}</option>)}</select></label>{template&&<div className="template-preview"><strong>{template.name}</strong><span>{template.description}</span><small>{template.requirements.filter((r)=>r[3]).length} required gates · {template.requirements.length} total checks</small></div>}<div className="modal-actions"><button type="button" className="soft-btn" onClick={onClose}>Cancel</button><button className="dark-btn" type="submit">Create room <Icon name="chevron" size={16}/></button></div></form></div></div>;
}

function BrandingPanel({workspace,onSave}){
  const [brandName,setBrandName]=useState(workspace.brandName||workspace.name);const [brandAccent,setBrandAccent]=useState(workspace.brandAccent||'#182018');const [customDomain,setCustomDomain]=useState(workspace.customDomain||'');const [saved,setSaved]=useState(false);const [error,setError]=useState('');
  return <section className="panel-section brand-panel" id="branding"><div className="panel-title"><div><span className="page-kicker">Agency identity</span><h2>Your client room, your brand.</h2></div><div className="brand-live-swatch" style={{background:brandAccent}}>{(brandName||workspace.name).slice(0,1).toUpperCase()}</div></div><form className="branding-form" onSubmit={async(e)=>{e.preventDefault();setError('');try{await onSave({brandName,brandAccent,customDomain});setSaved(true);setTimeout(()=>setSaved(false),1400);}catch(err){setError(err.message);}}}><label>Client-facing brand<input value={brandName} onChange={(e)=>setBrandName(e.target.value)} maxLength={120}/></label><label>Accent<input type="color" value={brandAccent} onChange={(e)=>setBrandAccent(e.target.value)}/></label><label>Custom review domain<input value={customDomain} onChange={(e)=>setCustomDomain(e.target.value)} placeholder="review.youragency.com"/><small>Domain routing/DNS still requires deployment configuration.</small></label><button className="soft-btn">{saved?'Saved ✓':'Save identity'}</button></form>{error&&<div className="form-alert error">{error}</div>}</section>;
}

export default function FinalizeDashboard(){
  const store=useFinalizeStore();const [creating,setCreating]=useState(false);const [defaultTemplate,setDefaultTemplate]=useState('');const active=store.finalizations.filter((f)=>f.state!=='FINALIZED');const completed=store.finalizations.filter((f)=>f.state==='FINALIZED');const blockerCount=active.reduce((n,f)=>n+readiness(f).blockers.length,0);const waitingApprovals=active.filter((f)=>f.approval.status==='pending').length;
  function openCreate(templateKey=''){setDefaultTemplate(templateKey);setCreating(true);}
  return <AppShell workspace={store.workspace} finalizations={store.finalizations}><div className="dashboard-head"><div><span className="page-kicker">Agency completion workspace</span><h1>Bring the last 10% home.</h1><p>Client feedback, files, access, payments, privacy, approval, and proof—without another project-management system.</p></div><button className="dark-btn" onClick={()=>openCreate()}><Icon name="plus"/>New finalization</button></div>
    <div className="metric-grid"><div className="metric"><span>Active</span><strong>{active.length}</strong><small>Finalizations in motion</small></div><div className="metric warning"><span>Open gates</span><strong>{blockerCount}</strong><small>Cross-system completion blockers</small></div><div className="metric"><span>Waiting approval</span><strong>{waitingApprovals}</strong><small>Version-bound client yeses</small></div><div className="metric success"><span>Finalized</span><strong>{completed.length}</strong><small>Proof records sealed</small></div></div>
    <section className="panel-section" id="active"><div className="panel-title"><div><span className="page-kicker">Active finalizations</span><h2>What’s left?</h2></div><span className="quiet-label">{active.length} active</span></div><div className="finalization-list">{active.map((f)=>{const info=readiness(f);return <Link className="finalization-row" href={`/app/f/${f.id}`} key={f.id}><div className={`room-icon ${info.blockers.length?'blocked':'ready'}`}>{info.blockers.length?info.blockers.length:'✓'}</div><div className="fin-main"><strong>{f.title}</strong><small>{f.client} · {f.type}</small></div><div className="fin-progress"><div><span>Readiness</span><b>{info.score}%</b></div><i><em style={{width:`${info.score}%`}}/></i></div><div className="fin-status"><span className={`status-pill ${info.blockers.length?'blocked':'ready'}`}>{info.blockers.length?`${info.blockers.length} gate${info.blockers.length===1?'':'s'}`:f.approval.status==='pending'?'Approval pending':'Ready'}</span><small>Due {f.dueLabel}</small></div><Icon name="chevron"/></Link>;})}</div></section>
    <section className="panel-section" id="templates"><div className="panel-title"><div><span className="page-kicker">Finalize Specs</span><h2>Start with a real definition of done.</h2></div><span className="quiet-label">Reusable templates</span></div><div className="template-grid">{store.templates.map((t)=><button className="template-card" key={t.key} onClick={()=>openCreate(t.key)}><div className="template-icon">✓</div><div><span>{t.category}</span><strong>{t.name}</strong><p>{t.description}</p><small>{t.requirements.filter((r)=>r[3]).length} required gates · {t.requirements.length} checks</small></div><Icon name="chevron" size={16}/></button>)}</div></section>
    <BrandingPanel workspace={store.workspace} onSave={store.updateBranding}/>
    <section className="panel-section" id="completed"><div className="panel-title"><div><span className="page-kicker">Proof of completion</span><h2>Recently finalized</h2></div></div>{completed.map((f)=><Link className="record-row" key={f.id} href={`/app/f/${f.id}`}><span className="record-seal">✓</span><div><strong>{f.title}</strong><small>{f.record?.id} · Version {f.record?.artifactVersion} · {f.record?.finalizedAt}</small></div><span className="status-pill finalized">Finalized</span></Link>)}</section>
    <section className="trust-strip"><Icon name="shield" size={22}/><div><strong>{store.remoteMode?'Persistent trust mode is active.':'Demo mode keeps the trust boundary explicit.'}</strong><span>{store.remoteMode?'Room mutations are authenticated server actions. Client review, secure uploads, encrypted access requests, and file processing all use scoped server paths.':'Room state stays in this browser. Connect Supabase + S3 + a vault key to activate production persistence, secure guest uploads, and encrypted access submissions.'}</span></div></section>
    {creating&&<NewFinalization onClose={()=>setCreating(false)} onCreate={store.createFinalization} templates={store.templates} defaultTemplate={defaultTemplate}/>}</AppShell>;
}
