'use client';

import { useEffect, useState } from 'react';
import { AppShell } from '../../../components/app-shell';
import { Icon } from '../../../components/icons';
import { useFinalizeStore } from '../../../lib/finalize-store';

const META={github:['GitHub','GH'],vercel:['Vercel','▲'],stripe:['Stripe','$'],docusign:['E-signature','✎'],google_drive:['Google Drive','D'],generic:['Generic webhook','↗']};

export default function IntegrationsPage(){
  const store=useFinalizeStore(); const [connections,setConnections]=useState([]); const [error,setError]=useState('');
  useEffect(()=>{if(!store.hydrated)return;if(!store.remoteMode){const map=new Map();for(const f of store.finalizations)for(const c of f.integrationConnections||[])map.set(c.id,c);setConnections([...map.values()]);return;}fetch('/api/integrations',{cache:'no-store'}).then(async(r)=>{const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error);setConnections(d.connections||[]);}).catch((e)=>setError(e.message));},[store.hydrated,store.remoteMode,store.finalizations]);
  if(!store.hydrated)return <div className="loading-screen">Loading integrations…</div>;
  return <AppShell workspace={store.workspace} finalizations={store.finalizations} activeSection="integrations"><div className="privacy-page integration-workspace-page"><section className="privacy-hero"><div><span className="page-kicker">Workspace control plane</span><h1>Integrations</h1><p>External systems provide signed evidence to Finalize. Connections are workspace-scoped; bindings decide which Finalization requirements they can change.</p></div><div className="privacy-posture"><div className="privacy-score"><strong>{connections.length}</strong><span>sources</span></div><div><strong>{connections.filter((c)=>(c.status||'')==='connected').length} connected</strong><small>Secrets stay server-side</small></div></div></section>{error&&<div className="document-gate-alert"><span>!</span><div><strong>Could not load integrations</strong><p>{error}</p></div></div>}<section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Configured sources</span><h3>Sources of external truth</h3><p>Configure a provider inside any Finalize Room, then bind its signals to specific completion conditions.</p></div></div><div className="workspace-integration-list">{connections.length?connections.map((c)=>{const provider=c.provider;const [label,mark]=META[provider]||META.generic;return <div key={c.id}><span className={`provider-mark ${provider}`}>{mark}</span><div><strong>{c.displayName||c.display_name||label}</strong><small>{label} · {(c.authMode||c.auth_mode||'environment')} authentication</small></div><span className={`status-pill ${(c.status==='connected')?'finalized':c.status==='degraded'?'blocked':'waiting'}`}>{c.status||'configured'}</span><small>{c.lastSyncedAt||c.last_synced_at?`Last evidence ${c.lastSyncedAt||c.last_synced_at}`:'No evidence yet'}</small></div>}):<div className="empty-state">No external systems configured yet. Open a Finalize Room → Integrations to add one.</div>}</div></section><section className="detail-panel"><span className="page-kicker">Security model</span><h3>Evidence can change completion state. It cannot bypass trust.</h3><div className="integration-principles"><div><Icon name="shield"/><strong>Signed first</strong><span>Unsigned events are rejected in production unless explicitly enabled for local development.</span></div><div><Icon name="check"/><strong>Explicit bindings</strong><span>A provider event only affects the requirement it was deliberately bound to.</span></div><div><Icon name="archive"/><strong>Minimal retention</strong><span>Raw webhook payloads are hashed and discarded; normalized evidence is retained.</span></div></div></section></div></AppShell>;
}
