'use client';

import { useMemo, useState } from 'react';
import { Icon } from './icons';
import { analyzePackageProfiles } from '../lib/documents/package';

const TYPES=['GENERIC','CONTRACT','PROPOSAL','APPLICATION','REPORT'];
const LABELS={GENERIC:'General document',CONTRACT:'Contract',PROPOSAL:'Proposal',APPLICATION:'Application',REPORT:'Report'};

function scoreClass(score){if(score==null)return 'muted';if(score>=90)return 'good';if(score>=70)return 'warn';return 'bad';}
function statusText(value=''){return String(value||'').replaceAll('_',' ').toLowerCase();}

function FindingRow({finding,artifact,store,finalizationId}){
  const [note,setNote]=useState('');
  const [open,setOpen]=useState(false);
  const active=finding.status==='OPEN';
  return <div className={`doc-finding ${finding.severity.toLowerCase()} ${active?'':'closed'}`}>
    <div className="doc-severity">{finding.severity==='BLOCKER'?'!':finding.severity==='WARNING'?'△':'i'}</div>
    <div className="doc-finding-copy"><div><strong>{finding.title}</strong><span className={`doc-source ${finding.source.toLowerCase()}`}>{finding.source}</span></div><p>{finding.detail}</p>{finding.evidence?.snippet&&<blockquote>{finding.evidence.snippet}</blockquote>}<small>{artifact.name} · {finding.ruleKey.replaceAll('_',' ')}{finding.artifactVersion?` · v${finding.artifactVersion}`:''}{finding.evidence?.confidence!=null?` · confidence ${Math.round(finding.evidence.confidence*100)}%`:''}</small>{finding.resolutionNote&&<small>Resolution note: {finding.resolutionNote}</small>}</div>
    <div className="doc-finding-actions">{active?<><button className="soft-btn small" onClick={()=>setOpen(!open)}>Resolve</button>{finding.source==='AI'&&finding.severity!=='BLOCKER'&&<button className="text-action" onClick={()=>store.confirmDocumentFindingBlocker(finalizationId,finding.id)}>Make blocker</button>}<button className="text-action" onClick={()=>store.setDocumentFindingStatus(finalizationId,finding.id,'WAIVED','Accepted intentionally by workspace member')}>Waive</button></>:<button className="text-action" onClick={()=>store.setDocumentFindingStatus(finalizationId,finding.id,'OPEN','')}>Reopen</button>}</div>
    {open&&<div className="doc-resolution"><input autoFocus value={note} onChange={(e)=>setNote(e.target.value)} placeholder="How was this resolved? (optional)"/><button className="dark-btn small" onClick={async()=>{await store.setDocumentFindingStatus(finalizationId,finding.id,'RESOLVED',note);setOpen(false);}}>Mark resolved</button></div>}
  </div>;
}

function DocumentArtifactCard({artifact,finalization,store}){
  const profile=artifact.documentProfile; const findings=(artifact.documentFindings||[]).filter(f=>f.artifactVersion==null||Number(f.artifactVersion)===Number(finalization.artifactVersion)); const blockers=findings.filter(f=>f.status==='OPEN'&&f.severity==='BLOCKER').length; const warnings=findings.filter(f=>f.status==='OPEN'&&f.severity==='WARNING').length; const refs=artifact.documentReferences||[]; const missing=refs.filter(r=>!r.present).length;
  const type=artifact.documentTypeOverride||profile?.documentType||artifact.documentType||'GENERIC';
  return <section className="detail-panel doc-artifact-card"><div className="doc-artifact-head"><div><span className="page-kicker">Document artifact</span><h3>{artifact.name}</h3><p>{profile?.title&&profile.title!==artifact.name?profile.title:'Structured completeness and execution-readiness review.'}</p></div><div className={`doc-score ${scoreClass(profile?.score??artifact.documentScore)}`}><strong>{profile?.score??artifact.documentScore??'—'}</strong><span>Document</span></div></div>
    <div className="doc-meta-grid"><div><span>Type</span><select value={type} onChange={(e)=>store.setDocumentType(finalization.id,artifact.id,e.target.value)}>{TYPES.map(t=><option key={t} value={t}>{LABELS[t]}</option>)}</select></div><div><span>Analysis</span><strong>{statusText(artifact.documentAnalysisStatus||'PENDING')}</strong></div><div><span>Open blockers</span><strong>{blockers}</strong></div><div><span>Warnings</span><strong>{warnings}</strong></div><div><span>References</span><strong>{refs.length}</strong></div><div><span>Missing refs</span><strong>{missing}</strong></div></div>
    <div className="doc-ai-boundary"><Icon name="shield" size={16}/><div><strong>{artifact.safeForAi?'Semantic AI review permitted by Privacy Firewall':'Deterministic review only'}</strong><span>{artifact.safeForAi?'Only the privacy-minimized AI derivative is eligible for semantic review.':artifact.aiBlockedReason?`AI blocked: ${artifact.aiBlockedReason.replaceAll('_',' ')}`:'AI is never required for deterministic document completeness checks.'}</span></div></div>
    {profile&&<div className="doc-profile-strip"><div><span>Words</span><strong>{profile.metrics?.words??'—'}</strong></div><div><span>Headings</span><strong>{profile.metrics?.headings??'—'}</strong></div><div><span>Dates</span><strong>{profile.entities?.dates?.length??0}</strong></div><div><span>Legal entities</span><strong>{profile.entities?.legalEntities?.length??0}</strong></div><div><span>Currencies</span><strong>{profile.entities?.currencies?.join(', ')||'—'}</strong></div></div>}
    <div className="doc-card-actions"><button className="soft-btn small" onClick={()=>store.reanalyzeDocument(finalization.id,artifact.id)}><Icon name="refresh" size={14}/>Re-run document checks</button></div>
  </section>;
}

export function DocumentCenter({finalization,store}){
  const artifacts=(finalization.artifacts||[]).filter(a=>['pdf','docx','pptx','xlsx','txt','md','csv','json'].some(ext=>a.name?.toLowerCase().endsWith(`.${ext}`))||a.documentProfile||a.documentAnalysisStatus);
  const findings=useMemo(()=>artifacts.flatMap(a=>(a.documentFindings||[]).filter(f=>f.artifactVersion==null||Number(f.artifactVersion)===Number(finalization.artifactVersion)).map(f=>({...f,artifact:a}))),[artifacts,finalization.artifactVersion]);
  const openBlockers=findings.filter(f=>f.status==='OPEN'&&f.severity==='BLOCKER'); const openWarnings=findings.filter(f=>f.status==='OPEN'&&f.severity==='WARNING');
  const references=artifacts.flatMap(a=>(a.documentReferences||[]).map(r=>({...r,artifact:a}))); const missing=references.filter(r=>!r.present);
  const analyzed=artifacts.filter(a=>a.documentProfile); const avg=analyzed.length?Math.round(analyzed.reduce((n,a)=>n+Number(a.documentProfile?.score||0),0)/analyzed.length):null;
  const packageObservations=analyzePackageProfiles(analyzed.map(a=>({...a.documentProfile,artifactId:a.id})));
  return <div className="document-center">
    <div className="document-hero"><div><span className="page-kicker">Phase 4 · Finalize Documents</span><h2>Is the document package actually ready?</h2><p>Finalize checks structure, placeholders, signatures, cross-document references, missing attachments, currencies, dates, and vertical-specific completion rules. Blocking findings become part of the Finalize gate.</p></div><div className="document-hero-actions"><button className="soft-btn" onClick={()=>store.reanalyzeDocumentPackage(finalization.id)}><Icon name="refresh" size={15}/>Re-check package</button>{store.remoteMode&&<a className="dark-btn" href={`/api/finalizations/${finalization.id}/documents/report`} target="_blank" rel="noreferrer"><Icon name="archive" size={15}/>Export document report</a>}</div></div>
    <div className="doc-stat-grid"><div><span>Documents analyzed</span><strong>{analyzed.length}/{artifacts.length}</strong></div><div className={openBlockers.length?'danger':'good'}><span>Blocking findings</span><strong>{openBlockers.length}</strong></div><div className={openWarnings.length?'warn':''}><span>Warnings</span><strong>{openWarnings.length}</strong></div><div className={missing.length?'danger':'good'}><span>Missing references</span><strong>{missing.length}</strong></div><div><span>Package score</span><strong>{avg??'—'}</strong></div></div>
    {openBlockers.length>0&&<div className="document-gate-alert"><span>!</span><div><strong>{openBlockers.length} document blocker{openBlockers.length===1?'':'s'} prevent final approval.</strong><p>Resolve or explicitly waive each blocker before this Finalization can cross the completion gate.</p></div></div>}
    {!artifacts.length?<div className="detail-panel empty-state">Upload a PDF, DOCX, PPTX, XLSX, TXT, Markdown, CSV, or JSON artifact to begin document analysis.</div>:<div className="doc-artifact-grid">{artifacts.map(a=><DocumentArtifactCard key={a.id} artifact={a} finalization={finalization} store={store}/>)}</div>}
    <section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Finding ledger</span><h3>{findings.length} evidence-backed finding{findings.length===1?'':'s'}</h3><p>Deterministic findings remain available even when privacy policy blocks external AI processing.</p></div><span className="status-pill muted">Evidence first</span></div><div className="doc-findings-list">{findings.length?findings.sort((a,b)=>({BLOCKER:0,WARNING:1,INFO:2}[a.severity]-{BLOCKER:0,WARNING:1,INFO:2}[b.severity])).map(f=><FindingRow key={f.id} finding={f} artifact={f.artifact} store={store} finalizationId={finalization.id}/>):<div className="empty-state">No document findings yet.</div>}</div></section>
    {packageObservations.length>0&&<section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Package consistency</span><h3>Cross-document observations</h3><p>Finalize compares structured metadata across related documents. These observations are advisory and require human judgment.</p></div><span className="status-pill muted">Human review</span></div><div className="doc-findings-list">{packageObservations.map(o=><div className="doc-finding warning" key={o.key}><div className="doc-severity">△</div><div className="doc-finding-copy"><div><strong>{o.title}</strong><span className="doc-source deterministic">PACKAGE</span></div><p>{o.detail}</p></div></div>)}</div></section>}
    <section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Package completeness</span><h3>Cross-document references</h3><p>References such as Schedule A, Exhibit B, Appendix 2, and attachments are checked against the files currently in this Finalization.</p></div><span className={`status-pill ${missing.length?'blocked':'finalized'}`}>{missing.length?`${missing.length} missing`:'Package references present'}</span></div><div className="doc-reference-table"><div className="doc-reference-head"><span>Referenced from</span><span>Reference</span><span>Status</span></div>{references.length?references.map(r=><div key={r.id}><span>{r.artifact.name}</span><strong>{r.rawText||`${r.type} ${r.label}`}</strong><span className={r.present?'ref-present':'ref-missing'}>{r.present?'✓ Present':'! Missing'}</span></div>):<div className="empty-state">No schedule, exhibit, appendix, annex, or attachment references detected.</div>}</div></section>
    {artifacts.some(a=>(a.documentProfile?.documentType||a.documentType)==='CONTRACT')&&<div className="doc-legal-boundary"><Icon name="shield" size={17}/><div><strong>Completeness review, not legal advice.</strong><span>Finalize can flag missing terms, attachments, placeholders, signature readiness, and inconsistencies. It does not determine legal enforceability or replace qualified counsel.</span></div></div>}
  </div>;
}
