'use client';

import { useEffect, useMemo, useState } from 'react';
import { Icon } from './icons';

const PROVIDER_META={
  github:{label:'GitHub',mark:'GH',hint:'CI checks, pull requests, commits and release evidence'},
  vercel:{label:'Vercel',mark:'▲',hint:'Production deployment readiness and release evidence'},
  stripe:{label:'Stripe',mark:'$',hint:'Payment, invoice and refund evidence'},
  docusign:{label:'E-signature',mark:'✎',hint:'Envelope completion and signature evidence'},
  google_drive:{label:'Google Drive',mark:'D',hint:'File/version change evidence'},
  generic:{label:'Generic webhook',mark:'↗',hint:'Bring any external completion signal into Finalize'},
};

function statusClass(status){return status==='connected'||status==='satisfied'?'finalized':status==='failed'||status==='degraded'?'blocked':status==='configured'||status==='waiting'?'waiting':'muted';}
function ago(value){if(!value)return 'Never';try{return new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));}catch{return String(value);}}

function ConnectionCard({connection, finalization, store, onBind, onSync}){
  const meta=PROVIDER_META[connection.provider]||PROVIDER_META.generic;
  const bindings=(finalization.integrationBindings||[]).filter((b)=>b.connectionId===connection.id);
  return <section className="integration-card">
    <div className="integration-card-head"><span className={`provider-mark ${connection.provider}`}>{meta.mark}</span><div><strong>{connection.displayName||meta.label}</strong><small>{meta.hint}</small></div><span className={`status-pill ${statusClass(connection.status)}`}>{connection.status}</span></div>
    <div className="integration-config"><span>Mode <strong>{connection.authMode||'environment'}</strong></span><span>Last evidence <strong>{ago(connection.lastSyncedAt)}</strong></span>{connection.config?.repository&&<span>Repo <strong>{connection.config.repository}</strong></span>}{connection.config?.projectId&&<span>Project <strong>{connection.config.projectId}</strong></span>}</div>
    <div className="binding-mini-list">{bindings.length?bindings.map((b)=><div key={b.id}><span className={`binding-dot ${b.status}`}/><div><strong>{b.signalKey}</strong><small>Expect “{b.expectedState}”{b.requirementTitle?` → ${b.requirementTitle}`:''}</small></div><span className={`status-pill ${statusClass(b.status)}`}>{b.status}</span></div>):<div className="empty-state compact">No completion condition is bound to this connection yet.</div>}</div>
    <div className="integration-card-actions"><button className="soft-btn small" onClick={()=>onBind(connection)}><Icon name="plus" size={14}/>Bind completion signal</button>{store.remoteMode&&['github','vercel'].includes(connection.provider)&&<button className="soft-btn small" onClick={()=>onSync(connection)}><Icon name="refresh" size={14}/>Sync now</button>}</div><code className="webhook-path">/api/integrations/webhooks/{connection.provider}?connection={connection.id}</code>
  </section>;
}

function BindingComposer({connection,finalization,onClose,onSave}){
  const meta=PROVIDER_META[connection.provider]||PROVIDER_META.generic;
  const signals={github:['github.workflow_run','github.check_suite','github.pull_request'],vercel:['vercel.deployment'],stripe:['stripe.payment','stripe.invoice'],docusign:['esign.envelope'],google_drive:['drive.file'],generic:['generic.signal']}[connection.provider]||['generic.signal'];
  const defaults={github:'success',vercel:'ready',stripe:'paid',docusign:'completed',google_drive:'updated',generic:'passed'};
  const [requirementId,setRequirementId]=useState(finalization.requirements.find((r)=>r.type==='integration'&&r.status!=='passed')?.id||finalization.requirements[0]?.id||'');
  const [signalKey,setSignalKey]=useState(signals[0]); const [expectedState,setExpectedState]=useState(defaults[connection.provider]||'passed');
  const matchMeta={github:['repository','Repository','owner/repo'],vercel:['projectId','Project ID','prj_…'],stripe:['objectId','Payment / invoice object ID','pi_… / in_… / cs_…'],docusign:['envelopeId','Envelope ID','envelope_…'],google_drive:['fileId','Drive file ID','1AbC…'],generic:['reference','Reference','external-id']}[connection.provider];
  const [match,setMatch]=useState(connection.config?.[matchMeta?.[0]]||'');
  async function submit(e){e.preventDefault();if(matchMeta&&!match.trim())return;const matcher={};if(matchMeta&&match)matcher[matchMeta[0]]=match.trim();await onSave({connectionId:connection.id,requirementId,signalKey,expectedState,matcher,required:true});onClose();}
  return <div className="integration-modal-backdrop" onClick={onClose}><form className="integration-modal" onSubmit={submit} onClick={(e)=>e.stopPropagation()}><div><span className="page-kicker">External evidence binding</span><h3>{meta.label} decides when this condition passes</h3><p>Finalize will only change the requirement when signed provider evidence matches this rule.</p></div><label>Requirement<select value={requirementId} onChange={(e)=>setRequirementId(e.target.value)}>{finalization.requirements.map((r)=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Signal<select value={signalKey} onChange={(e)=>setSignalKey(e.target.value)}>{signals.map((s)=><option key={s}>{s}</option>)}</select></label><label>Expected state<input value={expectedState} onChange={(e)=>setExpectedState(e.target.value)} placeholder="success / ready / paid / completed"/></label>{matchMeta&&<label>{matchMeta[1]}<input required value={match} onChange={(e)=>setMatch(e.target.value)} placeholder={matchMeta[2]}/></label>}<div className="integration-modal-actions"><button type="button" className="soft-btn" onClick={onClose}>Cancel</button><button className="dark-btn">Create binding</button></div></form></div>;
}

export function IntegrationCenter({finalization,store}){
  const [connections,setConnections]=useState([]); const [selected,setSelected]=useState(null); const [provider,setProvider]=useState('github'); const [configValue,setConfigValue]=useState(''); const [webhookSecret,setWebhookSecret]=useState(''); const [message,setMessage]=useState('');
  const demoConnections=useMemo(()=>finalization.integrationConnections||[],[finalization.integrationConnections]);
  useEffect(()=>{if(!store.remoteMode){setConnections(demoConnections);return;}let live=true;fetch('/api/integrations',{cache:'no-store'}).then((r)=>r.json().then((d)=>({ok:r.ok,d}))).then(({ok,d})=>{if(live&&ok)setConnections(d.connections||[]);}).catch(()=>{});return()=>{live=false};},[store.remoteMode,demoConnections]);
  async function addConnection(){setMessage('');if(!store.remoteMode){const c=store.addDemoIntegrationConnection(finalization.id,{provider,displayName:PROVIDER_META[provider].label,config:provider==='github'?{repository:configValue}:provider==='vercel'?{projectId:configValue}:{}});setConnections(c);return;}const config=provider==='github'?{repository:configValue}:provider==='vercel'?{projectId:configValue}:{};const response=await fetch('/api/integrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider,displayName:PROVIDER_META[provider].label,authMode:'environment',config,webhookSecret:provider==='stripe'?webhookSecret:undefined})});const data=await response.json();if(!response.ok){setMessage(data.detail||data.error||'Could not configure integration');return;}setConnections((items)=>[...items,data.connection]);setConfigValue('');setWebhookSecret('');setMessage(data.webhookSecret?`Webhook secret (shown once): ${data.webhookSecret}`:'Connection configured. Stripe signing secret remains server-side.');}
  async function saveBinding(payload){if(store.remoteMode)await store.bindIntegration(finalization.id,payload);else store.bindIntegration(finalization.id,payload);}
  async function syncConnection(connection){setMessage('');const response=await fetch(`/api/integrations/${connection.id}/sync`,{method:'POST'});const data=await response.json();if(!response.ok){setMessage(data.detail||data.error||'Sync failed');return;}await store.refresh();setMessage(`Observed ${data.observed?.signalKey||'external signal'}: ${data.observed?.state||'updated'}`);}
  const evidence=finalization.externalEvidence||[];
  return <div className="integration-center">
    <section className="integration-hero"><div><span className="page-kicker">Phase 5 · External evidence</span><h2>Let reality complete the checklist.</h2><p>GitHub, deployments, payments, signatures and file systems can satisfy Finalize requirements automatically. Evidence is minimized, versioned and auditable.</p></div><div className="integration-proof"><strong>{evidence.filter((e)=>e.status==='PASS').length}</strong><span>verified external signals</span><small>{(finalization.integrationBindings||[]).filter((b)=>b.status==='waiting').length} waiting</small></div></section>
    <div className="integration-principles"><div><Icon name="shield"/><strong>Signed events</strong><span>Provider webhook signatures are verified before evidence can change a gate.</span></div><div><Icon name="check"/><strong>Requirement-bound</strong><span>Events only act on explicit Finalization bindings, never arbitrary workspace state.</span></div><div><Icon name="archive"/><strong>Privacy-minimized</strong><span>Finalize stores normalized proof + SHA-256, not the full raw provider payload.</span></div></div>
    <div className="integration-grid">{connections.map((c)=><ConnectionCard key={c.id} connection={{...c,displayName:c.display_name||c.displayName,authMode:c.auth_mode||c.authMode,config:c.config_json||c.config||{},lastSyncedAt:c.last_synced_at||c.lastSyncedAt}} finalization={finalization} store={store} onBind={setSelected} onSync={syncConnection}/>)}</div>
    <section className="detail-panel integration-add"><div><span className="page-kicker">Add connection</span><h3>Connect another source of truth</h3><p>Phase 5 uses environment/OAuth-ready adapters. Provider secrets are never exposed to the browser.</p></div><select value={provider} onChange={(e)=>setProvider(e.target.value)}>{Object.entries(PROVIDER_META).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select>{provider==='github'&&<input value={configValue} onChange={(e)=>setConfigValue(e.target.value)} placeholder="owner/repository"/>}{provider==='vercel'&&<input value={configValue} onChange={(e)=>setConfigValue(e.target.value)} placeholder="Vercel project ID"/>}{provider==='stripe'&&<input type="password" value={webhookSecret} onChange={(e)=>setWebhookSecret(e.target.value)} placeholder="Stripe webhook signing secret (whsec_…)"/>}<button className="dark-btn" onClick={addConnection}>Configure</button>{message&&<small className="form-error">{message}</small>}</section>
    <section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Evidence ledger</span><h3>External facts that affected completion</h3><p>Every passing or failing signal is preserved independently from the requirement it changed.</p></div><span className="quiet-label">{evidence.length} observations</span></div><div className="evidence-ledger">{evidence.length?evidence.map((e)=><div key={e.id}><span className={`evidence-status ${String(e.status).toLowerCase()}`}>{e.status==='PASS'?'✓':e.status==='FAIL'?'!':'·'}</span><div><strong>{e.summary}</strong><small>{e.provider} · {ago(e.observedAt)}{e.signalKey?` · ${e.signalKey}`:''}</small></div>{e.reference&&<code>{e.reference}</code>}</div>):<div className="empty-state">No external evidence has been observed for this Finalization yet.</div>}</div></section>
    {!store.remoteMode&&<section className="integration-demo-strip"><div><span className="page-kicker">Demo controls</span><strong>See external evidence change a gate</strong></div><button className="soft-btn small" onClick={()=>store.simulateIntegrationEvidence(finalization.id,'stripe','paid')}>Simulate Stripe paid</button><button className="soft-btn small" onClick={()=>store.simulateIntegrationEvidence(finalization.id,'vercel','ready')}>Simulate Vercel ready</button><button className="soft-btn small" onClick={()=>store.simulateIntegrationEvidence(finalization.id,'github','success')}>Simulate GitHub success</button></section>}
    {selected&&<BindingComposer connection={selected} finalization={finalization} onClose={()=>setSelected(null)} onSave={saveBinding}/>}  
  </div>;
}
