'use client';

import { useMemo, useState } from 'react';
import { Icon } from './icons';

function money(cents,currency='CAD'){if(cents==null)return 'Amount not set';return new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(cents/100);}

export function RootBlockerGraph({info}){
  if(!info.rootBlockers?.length)return <div className="root-blocker-panel all-clear"><span className="root-node">✓</span><div><span className="page-kicker">Blocker intelligence</span><strong>No root blockers remain.</strong><small>The Finalize gate is now controlled by approval/version state.</small></div></div>;
  return <div className="root-blocker-panel"><div className="root-blocker-head"><div><span className="page-kicker">Blocker intelligence</span><h3>{info.rootBlockers.length} root cause{info.rootBlockers.length===1?'':'s'} explain {info.blockers.length} open gate{info.blockers.length===1?'':'s'}.</h3></div><span className="status-pill blocked">Exception first</span></div><div className="root-grid">{info.rootBlockers.slice(0,4).map((g)=><div className="root-card" key={g.root.id}><div className="root-node">!</div><div><strong>{g.root.title}</strong><small>{g.root.category||g.root.source||'Completion gate'}</small>{g.blocked.length>0&&<p>Blocks {g.blocked.length} dependent condition{g.blocked.length===1?'':'s'}.</p>}</div></div>)}</div></div>;
}

function ReviewMock({finalization,onAdd}){
  const [draft,setDraft]=useState(null);const [body,setBody]=useState('');const [shared,setShared]=useState(false);
  function click(e){const box=e.currentTarget.getBoundingClientRect();setDraft({x:Math.round(((e.clientX-box.left)/box.width)*1000)/10,y:Math.round(((e.clientY-box.top)/box.height)*1000)/10});setBody('');setShared(false);}
  return <div className="review-browser owner"><div className="review-browser-bar"><i/><i/><i/><span>{finalization.reviewUrl||'Add a review URL above'}</span></div><div className="review-surface" onClick={click}><div className="review-mock-nav"><b>ACME</b><span>Work&nbsp;&nbsp; Services&nbsp;&nbsp; About</span><em>Start a project</em></div><div className="review-mock-copy"><small>BUILT TO LAUNCH</small><h3>Good work deserves a clean finish.</h3><p>Version-aware feedback prevents accidental approval of work nobody actually reviewed.</p><button>Explore the project</button></div><div className="review-mock-card"><strong>Ready for launch?</strong><span>Everything important should be proven, not assumed.</span></div>{(finalization.annotations||[]).filter((a)=>a.artifactVersion===finalization.artifactVersion).map((a,i)=><button key={a.id} className={`review-pin ${a.status}`} style={{left:`${a.x}%`,top:`${a.y}%`}} onClick={(e)=>e.stopPropagation()} title={a.body}>{i+1}</button>)}{draft&&<div className="annotation-pop" style={{left:`${Math.min(72,draft.x)}%`,top:`${Math.min(72,draft.y)}%`}} onClick={(e)=>e.stopPropagation()}><strong>Internal review note</strong><textarea autoFocus value={body} onChange={(e)=>setBody(e.target.value)} placeholder="What should change here?"/><label className="annotation-visibility"><input type="checkbox" checked={shared} onChange={(e)=>setShared(e.target.checked)}/>Visible to client</label><div><button onClick={()=>setDraft(null)}>Cancel</button><button className="dark-btn small" onClick={async()=>{if(!body.trim())return;await onAdd({...draft,body,visibility:shared?'shared':'internal',targetRef:finalization.reviewUrl||'/'});setDraft(null);}}>Add note</button></div></div>}</div></div>;
}

export function ReviewPanel({finalization,store}){
  const [url,setUrl]=useState(finalization.reviewUrl||'');const current=(finalization.annotations||[]).filter((a)=>a.artifactVersion===finalization.artifactVersion);const old=(finalization.annotations||[]).filter((a)=>a.artifactVersion!==finalization.artifactVersion);
  return <div className="phase2-stack"><section className="detail-panel review-target-panel"><div className="panel-title-row"><div><span className="page-kicker">Version-aware review</span><h3>Review target · artifact v{finalization.artifactVersion}</h3><p>Feedback and approval stay bound to the exact artifact version that was reviewed.</p></div>{finalization.approval.status==='superseded'&&<span className="status-pill blocked">Prior approval superseded</span>}</div><form className="review-url-form" onSubmit={async(e)=>{e.preventDefault();await store.updateReviewUrl(finalization.id,url);}}><input value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="https://staging.example.com"/><button className="soft-btn small">Save review target</button>{!store.remoteMode&&<button type="button" className="soft-btn small" onClick={()=>store.bumpDemoVersion(finalization.id)}>Simulate new version</button>}</form><ReviewMock finalization={finalization} onAdd={(payload)=>store.addAnnotation(finalization.id,payload)}/></section><section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Feedback ledger</span><h3>{current.filter((a)=>a.status==='open').length} open on current version</h3></div><span className="quiet-label">{old.length} historical</span></div><div className="version-strip">{(finalization.versions||[]).slice(0,6).map((v)=><div key={v.id} className={v.versionNumber===finalization.artifactVersion?'current':''}><strong>v{v.versionNumber}</strong><span>{String(v.reason||'changed').replaceAll('_',' ')}</span><small>{v.createdAt}</small></div>)}</div><div className="annotation-ledger">{current.length?current.map((a,i)=><div key={a.id} className={a.status==='resolved'?'resolved':''}><span className="annotation-number">{i+1}</span><div><strong>{a.body}</strong><small>{a.targetRef||'Review surface'} · v{a.artifactVersion} · {a.visibility==='shared'?'shared with client':'internal'}</small></div>{a.status==='open'?<button className="soft-btn small" onClick={()=>store.resolveAnnotation(finalization.id,a.id)}>Resolve</button>:<span className="status-pill finalized">Resolved</span>}</div>):<div className="empty-state">No feedback on this version.</div>}</div></section></div>;
}

function AddFileRequest({finalization,store}){const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [description,setDescription]=useState('');if(!open)return <button className="soft-btn small" onClick={()=>setOpen(true)}><Icon name="plus" size={14}/>Request file</button>;return <form className="compact-form" onSubmit={async(e)=>{e.preventDefault();if(!title.trim())return;await store.addFileRequest(finalization.id,{title:title.trim(),description,acceptedExtensions:['pdf','zip','png','jpg','docx'],participantId:finalization.approval.reviewerId});setOpen(false);setTitle('');setDescription('');}}><input autoFocus value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="What file do you need?"/><input value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Why / accepted format"/><button className="dark-btn small">Create request</button><button type="button" className="soft-btn small" onClick={()=>setOpen(false)}>Cancel</button></form>}
function AddSecureRequest({finalization,store}){const [open,setOpen]=useState(false);const [title,setTitle]=useState('');if(!open)return <button className="soft-btn small" onClick={()=>setOpen(true)}><Icon name="plus" size={14}/>Request access</button>;return <form className="compact-form" onSubmit={async(e)=>{e.preventDefault();if(!title.trim())return;await store.addSecureRequest(finalization.id,{title:title.trim(),requestType:'credential',participantId:finalization.approval.reviewerId});setTitle('');setOpen(false);}}><input autoFocus value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Registrar, CMS, hosting access…"/><button className="dark-btn small">Secure request</button><button type="button" className="soft-btn small" onClick={()=>setOpen(false)}>Cancel</button></form>}
function AddPayment({finalization,store}){const [open,setOpen]=useState(false);const [label,setLabel]=useState('Final invoice');const [amount,setAmount]=useState('');if(!open)return <button className="soft-btn small" onClick={()=>setOpen(true)}><Icon name="plus" size={14}/>Add payment gate</button>;return <form className="compact-form" onSubmit={async(e)=>{e.preventDefault();await store.createPaymentGate(finalization.id,{label,amountCents:amount?Math.round(Number(amount)*100):null,currency:'CAD'});setOpen(false);}}><input value={label} onChange={(e)=>setLabel(e.target.value)} placeholder="Payment label"/><input value={amount} onChange={(e)=>setAmount(e.target.value)} type="number" step="0.01" min="0" placeholder="Amount CAD"/><button className="dark-btn small">Add gate</button><button type="button" className="soft-btn small" onClick={()=>setOpen(false)}>Cancel</button></form>}

export function ClientDeskPanel({finalization,store,copyShare}){
  const reviewer=finalization.participants.find((p)=>p.id===finalization.approval.reviewerId);const openFiles=(finalization.fileRequests||[]).filter((r)=>r.status==='requested').length;const openSecrets=(finalization.secureRequests||[]).filter((r)=>r.status==='requested').length;const unpaid=(finalization.paymentGates||[]).filter((g)=>!['paid','waived'].includes(g.status)).length;
  return <div className="phase2-stack"><div className="client-desk-hero"><div><span className="page-kicker">Client completion desk</span><h2>{openFiles+openSecrets+unpaid} external action{openFiles+openSecrets+unpaid===1?'':'s'} remain.</h2><p>Clients see only what they need to review, supply, pay, or approve. No project-management account required.</p></div><div className="client-desk-actions"><button className="soft-btn" onClick={copyShare}><Icon name="link" size={15}/>Copy client room</button><button className="dark-btn" disabled={!reviewer} onClick={()=>store.sendReminder(finalization.id,reviewer?.id)}><Icon name="message" size={15}/>Queue reminder</button></div></div><div className="agency-grid">
    <section className="detail-panel"><div className="mini-panel-head"><div><span className="page-kicker">File requests</span><h3>{openFiles} waiting</h3></div><AddFileRequest finalization={finalization} store={store}/></div><div className="closeout-list">{(finalization.fileRequests||[]).map((r)=><div key={r.id}><span className={`mini-state ${r.status==='received'?'pass':'open'}`}>{r.status==='received'?'✓':'↑'}</span><div><strong>{r.title}</strong><small>{r.description||'Secure requested-file upload'} · {(r.acceptedExtensions||[]).join(', ')||'project files'}</small></div>{r.status==='requested'&&<button className="mini-action" onClick={()=>store.completeFileRequest(finalization.id,r.id)}>Mark received</button>}</div>)}{!(finalization.fileRequests||[]).length&&<div className="empty-state">No client files requested.</div>}</div></section>
    <section className="detail-panel"><div className="mini-panel-head"><div><span className="page-kicker">Secure access</span><h3>{openSecrets} waiting</h3></div><AddSecureRequest finalization={finalization} store={store}/></div><div className="closeout-list">{(finalization.secureRequests||[]).map((r)=><div key={r.id}><span className={`mini-state ${r.status==='requested'?'open':'pass'}`}>{r.status==='requested'?'⌁':'✓'}</span><div><strong>{r.title}</strong><small>{r.status==='requested'?'Waiting for encrypted submission':`Vault status: ${r.status}`}</small></div>{['submitted','viewed'].includes(r.status)&&<button className="mini-action danger" onClick={()=>store.destroySecureRequest(finalization.id,r.id)}>Destroy secret</button>}</div>)}{!(finalization.secureRequests||[]).length&&<div className="empty-state">No secure access requests.</div>}</div></section>
    <section className="detail-panel"><div className="mini-panel-head"><div><span className="page-kicker">Payment gates</span><h3>{unpaid} unresolved</h3></div><AddPayment finalization={finalization} store={store}/></div><div className="closeout-list">{(finalization.paymentGates||[]).map((g)=><div key={g.id}><span className={`mini-state ${g.status==='paid'?'pass':'open'}`}>{g.status==='paid'?'✓':'$'}</span><div><strong>{g.label}</strong><small>{money(g.amountCents,g.currency)} · {g.providerReference||g.provider}</small></div>{g.status!=='paid'?<button className="mini-action" onClick={()=>store.setPaymentStatus(finalization.id,g.id,'paid')}>Mark paid</button>:<span className="status-pill finalized">Paid</span>}</div>)}{!(finalization.paymentGates||[]).length&&<div className="empty-state">No payment gate yet.</div>}</div></section>
    <section className="detail-panel"><div className="mini-panel-head"><div><span className="page-kicker">Reminder history</span><h3>Client chasing, controlled</h3></div></div><div className="closeout-list">{(finalization.reminders||[]).slice(0,5).map((r)=><div key={r.id}><span className={`mini-state ${r.status==='sent'?'pass':'open'}`}>↗</span><div><strong>{r.subject}</strong><small>{r.status} · {r.sendAt}</small></div></div>)}{!(finalization.reminders||[]).length&&<div className="empty-state">No reminders queued yet.</div>}</div></section>
  </div></div>;
}

function AddPrivacy({finalization,store}){const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [type,setType]=useState('access');if(!open)return <button className="soft-btn small" onClick={()=>setOpen(true)}><Icon name="plus" size={14}/>Add cleanup</button>;return <form className="compact-form" onSubmit={async(e)=>{e.preventDefault();if(!title.trim())return;await store.addPrivacyItem(finalization.id,{title:title.trim(),itemType:type,required:true});setOpen(false);setTitle('');}}><input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="What must be cleaned up?"/><select value={type} onChange={(e)=>setType(e.target.value)}><option value="access">Access</option><option value="credential">Credential</option><option value="guest_link">Guest link</option><option value="temporary_file">Temporary file</option><option value="test_account">Test account</option><option value="retention">Retention</option></select><button className="dark-btn small">Add</button><button type="button" className="soft-btn small" onClick={()=>setOpen(false)}>Cancel</button></form>}

export function CloseoutPanel({finalization,store}){
  const privacy=finalization.privacyItems||[];const open=privacy.filter((i)=>i.required&&!['resolved','waived','scheduled'].includes(i.status));const readinessSummary=useMemo(()=>({artifacts:(finalization.artifacts||[]).filter((a)=>a.status==='READY').length,requirements:(finalization.requirements||[]).filter((r)=>['passed','waived'].includes(r.status)).length}),[finalization]);
  function downloadDemo(){const manifest={schema:'finalize.handoff.demo.v1',generatedAt:new Date().toISOString(),finalization:{id:finalization.id,title:finalization.title,state:finalization.state,artifactVersion:finalization.artifactVersion},requirements:finalization.requirements,approval:finalization.approval,payments:finalization.paymentGates||[],privacyCloseout:finalization.privacyItems||[],note:'Demo manifest excludes secrets by design.'};const url=URL.createObjectURL(new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${finalization.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-finalize-handoff.json`;a.click();URL.revokeObjectURL(url);}
  return <div className="phase2-stack"><div className="closeout-hero"><div><span className="page-kicker">Handoff + privacy finalization</span><h2>Done means delivered, proven, and cleaned up.</h2><p>Finalize should not leave temporary access, credentials, guest links, or forgotten client data behind the project.</p></div>{store.remoteMode?<a className="dark-btn" href={`/api/finalizations/${finalization.id}/handoff`} target="_blank" rel="noreferrer"><Icon name="archive" size={15}/>Download handoff manifest</a>:<button className="dark-btn" onClick={downloadDemo}><Icon name="archive" size={15}/>Download demo manifest</button>}</div><div className="agency-grid two"><section className="detail-panel"><div className="mini-panel-head"><div><span className="page-kicker">Privacy closeout</span><h3>{open.length} cleanup blocker{open.length===1?'':'s'}</h3></div><AddPrivacy finalization={finalization} store={store}/></div><div className="closeout-list">{privacy.map((i)=><div key={i.id}><span className={`mini-state ${['resolved','scheduled','waived'].includes(i.status)?'pass':'open'}`}>{['resolved','scheduled','waived'].includes(i.status)?'✓':'!'}</span><div><strong>{i.title}</strong><small>{i.description||i.itemType.replaceAll('_',' ')}</small></div>{i.status==='open'?<button className="mini-action" onClick={()=>store.setPrivacyItemStatus(finalization.id,i.id,'resolved')}>Resolve</button>:<span className="status-pill finalized">{i.status}</span>}</div>)}{!privacy.length&&<div className="empty-state">No privacy cleanup items.</div>}</div></section><section className="detail-panel"><span className="page-kicker">Handoff proof</span><h3>Portable completion manifest</h3><p>The manifest lists the artifact version, requirement evidence, approval, payments, privacy closeout, and cryptographic artifact hashes available at generation time.</p><div className="handoff-stats"><div><span>Ready artifacts</span><strong>{readinessSummary.artifacts}</strong></div><div><span>Passed conditions</span><strong>{readinessSummary.requirements}</strong></div><div><span>Artifact version</span><strong>v{finalization.artifactVersion}</strong></div><div><span>Handoff state</span><strong>{finalization.handoffStatus||'NOT_STARTED'}</strong></div></div><div className="privacy-promise"><Icon name="shield" size={18}/><div><strong>Secrets are never placed in handoff manifests.</strong><span>Only request status and audit proof are included—not encrypted credential payloads.</span></div></div></section></div></div>;
}
