'use client';

import { useEffect, useMemo, useState } from 'react';
import { Icon } from './icons';

const DEMO_SETTINGS = {
  aiProcessingEnabled: true, allowBusinessAi: true, allowConfidentialAi: false, allowRestrictedAi: false, requireRedactionForAi: true,
  sourceRetentionDays: 30, derivedRetentionDays: 30, evidenceRetentionDays: 365, guestLinkTtlDays: 7,
  autoRevokeGuestsOnFinalize: true, autoDestroyCredentialsOnFinalize: true, dataRegion: 'north-america', trainingUse: 'NEVER',
};

function demoOverview(finalizations) {
  const artifacts = finalizations.flatMap((f) => (f.artifacts || []).map((a) => ({ ...a, finalizationId: f.id, finalizationTitle: f.title })));
  const piiTotals = {};
  for (const a of artifacts) for (const [k,v] of Object.entries(a.piiSummary || {})) piiTotals[k] = (piiTotals[k] || 0) + Number(v || 0);
  const privacyCounts = artifacts.reduce((m,a) => { const k=a.privacy||'BUSINESS';m[k]=(m[k]||0)+1;return m; },{});
  const liveSecrets = finalizations.flatMap((f) => f.secureRequests || []).filter((r) => ['submitted','viewed'].includes(r.status)).length;
  const openCloseoutItems = finalizations.flatMap((f) => f.privacyItems || []).filter((i) => i.required && !['resolved','waived','scheduled'].includes(i.status)).length;
  const aiBlocked = artifacts.filter((a) => a.status === 'READY' && !a.safeForAi).length;
  const finalized = finalizations.filter((f) => f.state === 'FINALIZED');
  return {
    settings: DEMO_SETTINGS,
    posture: { score: Math.max(0,100-(liveSecrets*12+openCloseoutItems*6+aiBlocked*2)), activeGuests: finalizations.filter((f)=>f.shareToken&&f.state!=='FINALIZED').length, liveSecrets, openCloseoutItems, aiBlocked, finalized:finalized.length, privacyFinalized:finalized.filter((f)=>f.privacyCloseoutStatus==='COMPLETE').length },
    inventory: { totalArtifacts: artifacts.length, privacyCounts, piiTotals, artifacts: artifacts.map((a)=>({id:a.id,finalization_id:a.finalizationId,original_filename:a.name,status:a.status,privacy_classification:a.privacy,pii_summary:a.piiSummary,safe_for_ai:a.safeForAi,ai_blocked_reason:a.aiBlockedReason,retention_delete_after:a.retentionDeleteAfter})) },
    guestAccess: [], secureRequests: finalizations.flatMap((f)=>f.secureRequests||[]), closeoutItems: finalizations.flatMap((f)=>f.privacyItems||[]), disposalRequests: [], events: [], finalizations: finalizations.map((f)=>({id:f.id,title:f.title,state:f.state,privacy_closeout_status:f.privacyCloseoutStatus})),
  };
}

function Toggle({checked,onChange,label,detail,danger=false}) { return <label className={`privacy-toggle ${danger?'danger':''}`}><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/><i/></label>; }
function Stat({label,value,detail,tone=''}) { return <div className={`privacy-stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function human(key=''){return String(key).replaceAll('_',' ').replace(/\b\w/g,(m)=>m.toUpperCase());}

export function PrivacyCenter({store}) {
  const [data,setData]=useState(()=>demoOverview(store.finalizations)); const [loading,setLoading]=useState(store.remoteMode); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  const [settings,setSettings]=useState(data.settings);
  async function refresh(){ if(!store.remoteMode){const d=demoOverview(store.finalizations);setData(d);return;} setLoading(true);try{const r=await fetch('/api/privacy/overview',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error);setData(j);setSettings(j.settings);}catch(e){setMessage(e.message);}finally{setLoading(false);} }
  useEffect(()=>{refresh();},[store.finalizations.length]);
  async function save(){setSaving(true);setMessage('');try{if(store.remoteMode){const r=await fetch('/api/privacy/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(settings)});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error);setSettings(j.settings);await refresh();}setMessage('Privacy policy saved ✓');}catch(e){setMessage(e.message);}finally{setSaving(false);} }
  async function action(action,payload={}){if(!store.remoteMode){setMessage('Demo mode: action simulated locally.');return;}const r=await fetch('/api/privacy/actions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error);await refresh();}
  const pii=Object.entries(data.inventory?.piiTotals||{}).sort((a,b)=>b[1]-a[1]); const artifactRows=data.inventory?.artifacts||[];
  const nextDeletion=(data.disposalRequests||[]).find((r)=>r.status==='scheduled');
  return <div className="privacy-center">
    <div className="privacy-hero"><div><span className="page-kicker">Privacy & data control</span><h1>Know what you hold. Control where it goes.</h1><p>Finalize inventories sensitive information, limits AI access, expires temporary access, schedules disposal, and records the privacy lifecycle alongside the work itself.</p></div><div className="privacy-posture"><div className="privacy-score"><strong>{loading?'—':data.posture?.score??100}</strong><span>Privacy posture</span></div><div><strong>{data.posture?.score>=90?'Strong controls':'Review recommended'}</strong><small>{data.posture?.activeGuests||0} active guest links · {data.posture?.liveSecrets||0} live secrets</small></div></div></div>

    <div className="privacy-stat-grid"><Stat label="Artifacts inventoried" value={data.inventory?.totalArtifacts||0} detail="Source files tracked by lifecycle"/><Stat label="Sensitive findings" value={pii.reduce((n,[,v])=>n+Number(v||0),0)} detail={`${pii.length} detected categories`} tone="warning"/><Stat label="AI blocked" value={data.posture?.aiBlocked||0} detail="Ready files deliberately kept from AI"/><Stat label="Privacy finalized" value={`${data.posture?.privacyFinalized||0}/${data.posture?.finalized||0}`} detail="Completed work cleaned up" tone="success"/></div>

    <div className="privacy-grid two">
      <section className="detail-panel privacy-policy"><div className="panel-title-row"><div><span className="page-kicker">AI privacy firewall</span><h2>Only show AI what policy permits.</h2><p>These rules are enforced during artifact promotion. UI changes alone cannot bypass them.</p></div><span className="status-pill finalized">Finalize training: NEVER</span></div>
        <Toggle checked={settings.aiProcessingEnabled} onChange={(v)=>setSettings({...settings,aiProcessingEnabled:v})} label="AI processing enabled" detail="Master switch for workspace AI eligibility."/>
        <Toggle checked={settings.allowBusinessAi} onChange={(v)=>setSettings({...settings,allowBusinessAi:v})} label="Business artifacts" detail="Allow privacy-minimized business material to become AI-eligible."/>
        <Toggle checked={settings.allowConfidentialAi} onChange={(v)=>setSettings({...settings,allowConfidentialAi:v})} label="Confidential artifacts" detail="Off by default. Requires completed privacy scan and redaction."/>
        <Toggle checked={settings.allowRestrictedAi} onChange={(v)=>setSettings({...settings,allowRestrictedAi:v})} label="Restricted artifacts" detail="Highest-risk material. Keep disabled unless a deliberate policy exception is approved." danger/>
        <Toggle checked={settings.requireRedactionForAi} onChange={(v)=>setSettings({...settings,requireRedactionForAi:v})} label="Redaction required" detail="AI eligibility requires a privacy-minimized derivative rather than the raw original."/>
      </section>
      <section className="detail-panel"><span className="page-kicker">Retention defaults</span><h2>Data should have an exit date.</h2><p>Defaults apply to new work; individual artifacts can still be disposed sooner.</p><div className="retention-grid">
        <label>Source files<select value={settings.sourceRetentionDays} onChange={(e)=>setSettings({...settings,sourceRetentionDays:Number(e.target.value)})}>{[7,30,60,90,365].map((d)=><option key={d} value={d}>{d} days</option>)}</select></label>
        <label>Derived AI copies<select value={settings.derivedRetentionDays} onChange={(e)=>setSettings({...settings,derivedRetentionDays:Number(e.target.value)})}>{[1,7,30,60,90].map((d)=><option key={d} value={d}>{d} days</option>)}</select></label>
        <label>Evidence<select value={settings.evidenceRetentionDays} onChange={(e)=>setSettings({...settings,evidenceRetentionDays:Number(e.target.value)})}>{[30,90,180,365,730].map((d)=><option key={d} value={d}>{d} days</option>)}</select></label>
        <label>Guest links<select value={settings.guestLinkTtlDays} onChange={(e)=>setSettings({...settings,guestLinkTtlDays:Number(e.target.value)})}>{[1,3,7,14,30].map((d)=><option key={d} value={d}>{d} days</option>)}</select></label>
      </div><Toggle checked={settings.autoRevokeGuestsOnFinalize} onChange={(v)=>setSettings({...settings,autoRevokeGuestsOnFinalize:v})} label="Revoke guest access at Finalization" detail="Temporary review access closes when the record is sealed."/><Toggle checked={settings.autoDestroyCredentialsOnFinalize} onChange={(v)=>setSettings({...settings,autoDestroyCredentialsOnFinalize:v})} label="Destroy submitted credentials at Finalization" detail="Encrypted vault payloads are wiped after their purpose is fulfilled."/>
        <div className="privacy-save-row"><label>Policy region<select value={settings.dataRegion} onChange={(e)=>setSettings({...settings,dataRegion:e.target.value})}><option value="north-america">North America</option><option value="canada">Canada policy target</option><option value="united-states">United States policy target</option><option value="europe">Europe policy target</option><option value="custom">Custom</option></select></label><button className="dark-btn" onClick={save} disabled={saving}>{saving?'Saving…':'Save privacy policy'}</button></div>{message&&<small className="privacy-message">{message}</small>}
      </section>
    </div>

    <div className="privacy-grid two">
      <section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Data inventory</span><h2>What Finalize currently knows.</h2></div><a className="soft-btn small" href={store.remoteMode?'/api/privacy/export':'#'} onClick={(e)=>{if(!store.remoteMode){e.preventDefault();setMessage('Connect production persistence to export the privacy manifest.');}}}><Icon name="archive" size={14}/>Export manifest</a></div><div className="pii-inventory">{pii.length?pii.map(([k,v])=><div key={k}><span>{human(k)}</span><strong>{v}</strong></div>):<div className="empty-state">No sensitive-data findings recorded yet.</div>}</div><div className="classification-bar">{['PUBLIC','BUSINESS','CONFIDENTIAL','RESTRICTED'].map((k)=><div key={k}><span>{k}</span><strong>{data.inventory?.privacyCounts?.[k]||0}</strong></div>)}</div></section>
      <section className="detail-panel"><span className="page-kicker">Exposure cleanup</span><h2>Temporary access should stay temporary.</h2><div className="exposure-list"><div><span className="mini-state open">↗</span><div><strong>{data.posture?.activeGuests||0} active guest links</strong><small>Review access that has not yet been revoked.</small></div><button className="mini-action danger" disabled={!data.posture?.activeGuests} onClick={()=>action('revoke_all_guest_links')}>Revoke all</button></div><div><span className="mini-state open">⌁</span><div><strong>{data.posture?.liveSecrets||0} live credentials</strong><small>Submitted/viewed vault payloads not yet destroyed.</small></div><button className="mini-action danger" disabled={!data.posture?.liveSecrets} onClick={()=>action('destroy_all_live_credentials')}>Destroy</button></div><div><span className={`mini-state ${data.posture?.openCloseoutItems?'open':'pass'}`}>{data.posture?.openCloseoutItems?'!':'✓'}</span><div><strong>{data.posture?.openCloseoutItems||0} privacy closeout blockers</strong><small>Required cleanup attached to active work.</small></div></div></div>{nextDeletion&&<div className="privacy-next-delete"><strong>Next scheduled disposal</strong><span>{nextDeletion.execute_after}</span></div>}</section>
    </div>

    <section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Artifact lifecycle</span><h2>Storage-safe does not automatically mean AI-safe.</h2></div><span className="quiet-label">Newest {Math.min(artifactRows.length,12)} shown</span></div><div className="privacy-artifact-table"><div className="privacy-table-head"><span>Artifact</span><span>Class</span><span>AI</span><span>Retention</span><span>Action</span></div>{artifactRows.slice(0,12).map((a)=><div key={a.id}><span><strong>{a.original_filename}</strong><small>{a.status}</small></span><span><em className={`classification ${String(a.privacy_classification).toLowerCase()}`}>{a.privacy_classification}</em></span><span>{a.safe_for_ai?<b className="ai-yes">Eligible</b>:<b className="ai-no">Blocked</b>}<small>{a.ai_blocked_reason||''}</small></span><span><small>{a.retention_delete_after||'Policy default'}</small></span><span>{a.status!=='DELETED'?<button className="mini-action danger" onClick={()=>action('schedule_artifact_deletion',{artifactId:a.id})}>Schedule delete</button>:<em>Deleted</em>}</span></div>)}{!artifactRows.length&&<div className="empty-state">Upload an artifact to start the privacy lifecycle.</div>}</div></section>
  </div>;
}

export function PrivacyRoomPanel({finalization,store}) {
  const artifacts=finalization.artifacts||[];const pii={};for(const a of artifacts)for(const[k,v]of Object.entries(a.piiSummary||{}))pii[k]=(pii[k]||0)+Number(v||0);const blocked=artifacts.filter((a)=>a.status==='READY'&&!a.safeForAi);const open=(finalization.privacyItems||[]).filter((i)=>i.required&&!['resolved','waived','scheduled'].includes(i.status));
  return <div className="phase2-stack"><div className="privacy-room-hero"><div><span className="page-kicker">Room privacy</span><h2>{open.length?`${open.length} privacy obligation${open.length===1?'':'s'} remain.`:'Privacy closeout is on track.'}</h2><p>Artifact classification, AI eligibility, temporary access, and cleanup stay attached to this Finalization—not hidden in a global policy page.</p></div><a className="soft-btn" href="/app/privacy"><Icon name="shield" size={15}/>Workspace Privacy Center</a></div><div className="privacy-grid two"><section className="detail-panel"><span className="page-kicker">Sensitive information</span><h3>{Object.values(pii).reduce((a,b)=>a+b,0)} findings across {artifacts.length} artifact{artifacts.length===1?'':'s'}</h3><div className="pii-inventory">{Object.entries(pii).map(([k,v])=><div key={k}><span>{human(k)}</span><strong>{v}</strong></div>)}{!Object.keys(pii).length&&<div className="empty-state">No sensitive-data findings recorded.</div>}</div></section><section className="detail-panel"><span className="page-kicker">AI boundary</span><h3>{blocked.length} artifact{blocked.length===1?'':'s'} deliberately blocked from AI</h3><div className="closeout-list">{artifacts.map((a)=><div key={a.id}><span className={`mini-state ${a.safeForAi?'pass':'open'}`}>{a.safeForAi?'✓':'×'}</span><div><strong>{a.name}</strong><small>{a.privacy} · {a.safeForAi?'privacy-minimized AI copy permitted':a.aiBlockedReason||'AI access not permitted'}</small></div></div>)}{!artifacts.length&&<div className="empty-state">No artifacts yet.</div>}</div></section></div><section className="detail-panel"><div className="panel-title-row"><div><span className="page-kicker">Privacy finalization</span><h3>Finish the data lifecycle too.</h3></div><span className={`status-pill ${open.length?'blocked':'finalized'}`}>{open.length?'Cleanup required':'Ready'}</span></div><div className="closeout-list">{(finalization.privacyItems||[]).map((i)=><div key={i.id}><span className={`mini-state ${['resolved','scheduled','waived'].includes(i.status)?'pass':'open'}`}>{['resolved','scheduled','waived'].includes(i.status)?'✓':'!'}</span><div><strong>{i.title}</strong><small>{i.description||human(i.itemType)}</small></div>{i.status==='open'&&<button className="mini-action" onClick={()=>store.setPrivacyItemStatus(finalization.id,i.id,'resolved')}>Resolve</button>}</div>)}</div></section></div>;
}
