import crypto from 'node:crypto';
import { NextResponse } from 'next/server';
import { createSupabaseAdminClient } from '../../../../../lib/supabase/admin';
import { ingestIntegrationEvent } from '../../../../../lib/integrations/evidence';
import { verifyHmac, verifyStripeSignature, PROVIDERS } from '../../../../../lib/integrations/providers';
import { decryptVaultPayload } from '../../../../../lib/vault';

function headerMap(headers){const out={};for(const [k,v] of headers.entries())out[k.toLowerCase()]=v;return out;}
export async function POST(request,{params}){const {provider}=await params;if(!PROVIDERS[provider])return NextResponse.json({error:'unsupported_provider'},{status:404});const rawBody=await request.text();let payload;try{payload=JSON.parse(rawBody);}catch{return NextResponse.json({error:'invalid_json'},{status:400});}const headers=headerMap(request.headers);const connectionId=new URL(request.url).searchParams.get('connection');if(!connectionId)return NextResponse.json({error:'connection_required'},{status:400});const db=createSupabaseAdminClient();const {data:connection,error}=await db.from('integration_connections').select('*').eq('id',connectionId).eq('provider',provider).maybeSingle();if(error||!connection)return NextResponse.json({error:'connection_not_found'},{status:404});let connectionWebhookSecret='';{const {data:secretRow}=await db.from('integration_secrets').select('encrypted_payload,payload_iv,payload_tag').eq('connection_id',connection.id).maybeSingle();if(secretRow){try{connectionWebhookSecret=decryptVaultPayload({ciphertext:secretRow.encrypted_payload,iv:secretRow.payload_iv,tag:secretRow.payload_tag}).webhookSecret||'';}catch{connectionWebhookSecret='';}}}let signatureValid=false;if(provider==='github')signatureValid=verifyHmac(rawBody,headers['x-hub-signature-256'],connectionWebhookSecret||process.env.FINALIZE_GITHUB_WEBHOOK_SECRET||'');else if(provider==='stripe')signatureValid=verifyStripeSignature(rawBody,headers['stripe-signature'],connectionWebhookSecret||process.env.FINALIZE_STRIPE_WEBHOOK_SECRET||'');else {const secret=connectionWebhookSecret||process.env[`FINALIZE_${provider.toUpperCase()}_WEBHOOK_SECRET`]||process.env.FINALIZE_GENERIC_WEBHOOK_SECRET||'';signatureValid=verifyHmac(rawBody,headers['x-finalize-signature'],secret);}
  const allowUnsigned=process.env.FINALIZE_ALLOW_UNSIGNED_WEBHOOKS==='true';if(!signatureValid&&!allowUnsigned)return NextResponse.json({error:'invalid_signature'},{status:401});
  try{const result=await ingestIntegrationEvent({db,organizationId:connection.organization_id,connection,provider,rawBody,payload,headers,signatureValid});return NextResponse.json({ok:true,matched:result.matched});}catch(err){await db.from('integration_connections').update({status:'degraded',last_error:String(err.message||err).slice(0,500),updated_at:new Date().toISOString()}).eq('id',connection.id);return NextResponse.json({error:'event_processing_failed',detail:err.message},{status:500});}
}
